apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  labels:
    service: adguard-home
spec:
  selector:
    matchLabels:
      service: adguard-home
  template:
    metadata:
      labels:
        service: adguard-home
    spec:
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:latest
          env:
          - name: USERSPACE
            valeu: "false"
          - name: TS_HOSTNAME
            value: "adguard"
          - name: DEST_PORT
            value: "3000"
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: tailscale
                key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      serviceAccount: tailscale
