---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  labels:
    service: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      service: unifi-controller
  template:
    metadata:
      labels:
        service: unifi-controller
    spec:
      serviceAccount: tailscale
      containers:
        - name: unifi-controller
          image: lscr.io/linuxserver/unifi-controller:7.2.92
          ports:
            - containerPort: 8443
              name: ubnt-8443
              protocol: TCP
            - containerPort: 3478
              name: ubnt-3478
              protocol: UDP
            - containerPort: 10001
              name: ubnt-10001
              protocol: UDP
            - containerPort: 8080
              name: ubnt-8080
              protocol: TCP
            - containerPort: 1900
              name: ubnt-1900
              protocol: UDP
            - containerPort: 8843
              name: ubnt-8843
              protocol: TCP
            - containerPort: 8880
              name: ubnt-8880
              protocol: TCP
            - containerPort: 6789
              name: ubnt-6789
              protocol: TCP
            - containerPort: 5514
              name: ubnt-5514
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: data
              subPath: unifi/config
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "300m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
              name: unifi-controller
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:latest
          env:
            - name: USERSPACE
              value: "false"
            - name: TS_HOSTNAME
              value: "unifi"
            - name: DEST_PORT
              value: "8080"
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: unifi-storage
