apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-svc
  labels:
    app: unifi-controller
spec:
  ports:
    - port: 80
      targetPort: 8443
      name: web-http
      protocol: TCP
    - port: 8080
      name: devices
      protocol: TCP
    - port: 8843
      name: guest-https
      protocol: TCP
    - port: 8880
      name: guest-http
      protocol: TCP
    - port: 6789
      name: mobile-test
      protocol: TCP
    - port: 3478
      name: stun
      protocol: UDP
    - port: 10001
      name: discovery
      protocol: UDP
    - port: 1900
      name: discoveryl2
      protocol: UDP
    - port: 5514
      name: syslog
      protocol: UDP
  selector:
    app: unifi-controller
