apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubenurse
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/postfinance/kubenurse.git'
    targetRevision: HEAD
    path: helm/kubenurse
    helm:
      releaseName: kubenurse
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: -1
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 30m
