apiVersion: v1
kind: Pod
metadata:
  name: subnet-router
  labels:
    app: tailscale
spec:
  selector:
    matchLabels:
      app: subnet-router
  replicas: 1
  template:
    metadata:
      labels:
        app: subnet-router
  serviceAccountName: "tailscale"
  containers:
  - name: tailscale
    imagePullPolicy: Always
    image: "docker.io/grubertech/tailscale:latest"
    env:
    - name: TS_HOSTNAME
      value: "router"
    - name: USERSPACE
      value: "true"
    - name: AUTH_KEY
      valueFrom:
        secretKeyRef:
          name: tailscale
          key: AUTH_KEY
          optional: true
    - name: ROUTES
      value: "10.43.0.1/16"
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      capabilities:
        add:
        - NET_ADMIN
    resources:
      limits:
        cpu: "256m"
        memory: "256Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"
