---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  labels:
    service: unifi-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      service: unifi-controller
  template:
    metadata:
      labels:
        service: unifi-controller
    spec:
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:latest
          env:
            - name: USERSPACE
              value: "false"
            - name: TS_HOSTNAME
              value: "unifi"
            - name: DEST_PORT
              value: "8080"
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      serviceAccount: tailscale