---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-server
  labels:
    service: n8n-server
spec:
  replicas: 1
  selector:
    matchLabels:
      service: n8n-server
  template:
    metadata:
      labels:
        service: n8n-server
    spec:
      serviceAccount: tailscale
      containers:
        - name: n8n
          image: n8nio/n8n:0.191.1
          envFrom:
            - configMapRef:
                name: n8n-cm
            - secretRef:
                name: n8n-vars
          ports:
            - name: web
              containerPort: 5678
              protocol: TCP
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1024Mi"
          volumeMounts:
            - name: config-storage
              mountPath: /home/node/.n8n
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:latest
          env:
          - name: USERSPACE
            value: "false"
          - name: TS_HOSTNAME
            value: "n8n"
          - name: DEST_PORT
            value: "5678"
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: tailscale
                key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: n8n-storage
