kind: Secret
apiVersion: v1
metadata:
  name: n8n-vars
  annotations:
    avp.kubernetes.io/path: "kv/n8n"
type: Opaque
data:
  DB_POSTGRESDB_DATABASE: <DB_POSTGRESDB_DATABASE>
  DB_POSTGRESDB_HOST: <DB_POSTGRESDB_HOST>
  DB_POSTGRESDB_PORT: <DB_POSTGRESDB_PORT>
  DB_POSTGRESDB_USER: <DB_POSTGRESDB_USER>
  N8N_BASIC_AUTH_PASSWORD: <N8N_BASIC_AUTH_PASSWORD>
  N8N_BASIC_AUTH_USER: <N8N_BASIC_AUTH_USER>
  N8N_ENCRYPTION_KEY: <N8N_ENCRYPTION_KEY>
