apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
  annotations:
    link.argocd.argoproj.io/external-link: http://homeassistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      initContainers:
        - name: git-sync
          image: k8s.gcr.io/git-sync/git-sync:v3.3.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: config-volume
            mountPath: /tmp/repository
          env:
          - name: GIT_SYNC_REPO
            value: https://github.com/gruberdev/homeassistant
          - name: GIT_SYNC_ROOT
            value: /tmp/repository
          - name: GIT_SYNC_PERMISSIONS
            value: "0777"
          - name: GIT_SYNC_ONE_TIME
            value: "true"
          - name: GIT_SYNC_BRANCH
            value: "main"
      containers:
        - env:
            - name: TZ
              value: America/Sao_Paulo
            - name: PYTHONWARNINGS
              value: ignore:Unverified HTTPS request
          image: homeassistant/home-assistant:2022.8
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            tcpSocket:
              port: 8123
            timeoutSeconds: 3
          name: home-assistant
          lifecycle:
            postStart:
              exec:
                command:
                  ['/bin/sh', '-c', 'cp -rf /config/homeassistant/* /config']
          ports:
            - containerPort: 8123
              name: api
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 30
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 750Mi
            requests:
              cpu: 200m
              memory: 128Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: ha-secrets
              mountPath: /config/secrets.yaml
              subPath: secrets.yaml
            - mountPath: /config
              name: config-volume
            - mountPath: /dev/ttyUSB0
              name: dev-usb-00
            - mountPath: /dev/ttyUSB1
              name: dev-usb-01
            - mountPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130205F-if00-port0
              name: zigbee-00
            - mountPath: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130205F-if01-port0
              name: zigbee-01
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - name: ha-secrets
          secret:
            secretName: ha-secrets
        - name: config-volume
          persistentVolumeClaim:
            claimName: home-assisstant-pvc
        - hostPath:
            path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130205F-if00-port0
          name: zigbee-00
        - hostPath:
            path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130205F-if01-port0
          name: zigbee-01
        - hostPath:
            path: /dev/ttyUSB0
          name: dev-usb-00
        - hostPath:
            path: /dev/ttyUSB1
          name: dev-usb-01
