kind: pipeline
name: Validate
type: docker

platform:
  os: linux
  arch: amd64
node:
  server: home
  arm: no
  docker: yes

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    - main

steps:
  - name: YAML Validate
    image: sdesbure/yamllint:latest
    commands:
      - yamllint -c ./.yamllint .

  - name: k8s Resources Validate
    image: grubertech/kubeval:latest
    commands:
      - /bin/sh -c 'task validate'
