kind: pipeline
name: Validate
type: docker

platform:
  os: linux
  arch: amd64
node:
  server: home
  arm: no
  docker: yes

trigger:
  event:
    include:
      - push
    exclude:
      - pull_request
  branch:
    - main

steps:
  - name: YAML Linter Validate
    image: sdesbure/yamllint:latest
    failure: ignore
    commands:
      - yamllint -c ./.yamllint .
