apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: links-cloudflare
spec:
  secretName: golinks-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: links.gruber.dev.br
  dnsNames:
    - links.gruber.dev.br
