apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  labels:
    app: drone
spec:
  selector:
    matchLabels:
      app: drone
  replicas: 1
  template:
    metadata:
      labels:
        app: drone
    spec:
      automountServiceAccountToken: false
      serviceAccount: tailscale
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:latest
          env:
          - name: USERSPACE
            valeu: "false"
          - name: TS_HOSTNAME
            value: "drone"
          - name: DEST_PORT
            value: "80"
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: tailscale
                key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
        - envFrom:
            - configMapRef:
                name: drone-server
            - secretRef:
                name: drone-server-vars
          image: 'drone/drone:2.12.1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          name: server
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - mountPath: /data
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: drone-storage
