apiVersion: v1
kind: Service
metadata:
  name: drone-server
  labels:
    app: drone
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: drone
  type: ClusterIP
