apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-internal
  labels:
    app: qbittorrent
  annotations:
    kube-vip.io/vipHost: qbittorrent
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: qbittorrent
  type: LoadBalancer
  loadBalancerIP: "192.168.1.103"
  loadBalancerClass: kube-vip.io/kube-vip-class

---
apiVersion: v1
kind: Service
metadata:
  name: torrent-tcp
  labels:
    app: qbittorrent
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: traffic
      port: 6881
      targetPort: 6881
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: torrent-udp
  labels:
    app: qbittorrent
spec:
  type: ClusterIP
  selector:
    app: qbittorrent
  ports:
    - name: traffic-udp
      port: 6881
      targetPort: 6881
      protocol: UDP
