apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.image-updater: apiKey
  url: https://argocd.gr.wtf
  statusbadge.enabled: "true"
  statusbadge.url: "https://status.argo.gr.wtf/"
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
