version: '3'
vars:
  CYAN: tput setaf 6
  RED: tput setaf 1
  YELLOW: tput setaf 3
  GREEN: tput setaf 2
  BLUE: tput setaf 1
  PURPLE: tput setaf 5
  BG_B: tput setab 0
  BOLD: tput bold
  RESET: tput sgr0
  CLEAR: tput reset
  PATH_ERROR: is not installed or correctly configured in PATH.
  WHATSAPP_VERSION: v0.7.1

silent: true

tasks:
  build:whats:
    cmds:
      - docker build -t docker.io/grubertech/whats-bridge:latest -t docker.io/grubertech/whats-bridge:{{.WHATSAPP_VERSION}} -f apps/matrix/bridges/whatsapp/Dockerfile .
    ignore_error: true

  push:whats:
    cmds:
      - docker push docker.io/grubertech/whats-bridge:latest
      - docker push docker.io/grubertech/whats-bridge:{{.WHATSAPP_VERSION}}
    ignore_error: true

  test:whats:
    cmds:
      - echo -e "Envsubst:\n"
      - docker run --rm --name whatsapp-bridge -it docker.io/grubertech/whats-bridge:latest /bin/sh -c 'envsubst'
      - echo -e "Testing bridge command:\n"
      - docker run --rm --name whatsapp-bridge -it docker.io/grubertech/whats-bridge:latest /bin/sh -c 'mautrix-whatsapp'
    ignore_error: true
