version: '3'
vars:
  CYAN: tput setaf 6
  RED: tput setaf 1
  YELLOW: tput setaf 3
  GREEN: tput setaf 2
  BLUE: tput setaf 1
  PURPLE: tput setaf 5
  BG_B: tput setab 0
  BOLD: tput bold
  RESET: tput sgr0
  CLEAR: tput reset
  PATH_ERROR: is not installed or correctly configured in PATH.

silent: true

tasks:
  n8n:
    cmds:
      - rm test/n8n-secret.yaml
      - |
        cat << EOF > test/n8n-secret.yaml
        apiVersion: v1
        kind: Secret
        metadata:
          name: n8n-vars
          namespace: services
        stringData:
          N8N_SMTP_HOST: $N8N_SMTP_HOST
          N8N_SMTP_PORT: $N8N_SMTP_PORT
          N8N_SMTP_USER: $N8N_SMTP_USER
          N8N_SMTP_PASS: $N8N_SMTP_PASS
          N8N_BASIC_AUTH_USER: $N8N_BASIC_AUTH_USER
          N8N_BASIC_AUTH_PASSWORD: $N8N_BASIC_AUTH_PASSWORD
          DB_POSTGRESDB_DATABASE: $DB_POSTGRESDB_DATABASE
          DB_POSTGRESDB_HOST: $DB_POSTGRESDB_HOST
          DB_POSTGRESDB_PORT: $DB_POSTGRESDB_PORT
          DB_POSTGRESDB_USER: $DB_POSTGRESDB_USER
          DB_POSTGRESDB_SCHEMA: $DB_POSTGRESDB_SCHEMA
          DB_POSTGRESDB_PASSWORD: $DB_POSTGRESDB_PASSWORD
        EOF
      - kubectl apply -f test/n8n-secret.yaml
      - rm test/n8n-secret.yaml
    ignore_error: true

  gen:
    cmds:
      - task: n8n
