apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
spec:
  project: monitoring
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: main
    path: charts/kube-prometheus-stack/crds/
    helm:
      skipCrds: true
      releaseName: kube-prometheus-crds
    directory:
      recurse: true
  destination:
    namespace: monitoring
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
