apiVersion: v1
kind: Service
metadata:
  name: monica
  labels:
    app: monica
spec:
  type: ClusterIP
  selector:
    app: monica
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
