apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  labels:
    app: changedetection
  annotations:
    link.argocd.argoproj.io/external-link: http://onchanges
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: changedetection
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      containers:
        - name: changedetection
          image: dgtlmoon/changedetection.io:0.39.19.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: onchanges-cm
          volumeMounts:
            - name: onchange-data
              mountPath: "/datastore"
      volumes:
        - name: onchange-data
          persistentVolumeClaim:
            claimName: onchange-storage
