apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: changedetection
  labels:
    app: changedetection
  annotations:
    link.argocd.argoproj.io/external-link: http://onchanges
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changedetection
  serviceName: "changedetection"
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      containers:
        - name: changedetection
          image: dgtlmoon/changedetection.io:latest
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 5000
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: onchanges-cm
          volumeMounts:
          - name: onchange-data
            mountPath: "/datastore"
      volumes:
      - name: onchange-data
        persistentVolumeClaim:
          claimName: onchange-storage
