apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base

namespace: matrix

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: node-two
  target:
    kind: Deployment
    name: element

commonAnnotations:
  reloader.stakater.com/auto: "true"
