apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/longhorn/longhorn.git'
    targetRevision: v1.2.5
    path: chart
    helm:
      releaseName: longhorn
      values: |
          global:
            cattle:
              systemDefaultRegistry: ""
              windowsCluster:
                # Enable this to allow Longhorn to run on the Rancher deployed Windows cluster
                enabled: false
                # Tolerate Linux node taint
                tolerations:
                - key: "cattle.io/os"
                  value: "linux"
                  effect: "NoSchedule"
                  operator: "Equal"
                # Select Linux nodes
                nodeSelector:
                  kubernetes.io/os: "linux"
                # Recognize toleration and node selector for Longhorn run-time created components
                defaultSetting:
                  taintToleration: cattle.io/os=linux:NoSchedule
                  systemManagedComponentsNodeSelector: kubernetes.io/os:linux
          image:
            longhorn:
              engine:
                repository: longhornio/longhorn-engine
                tag: v1.2.5
              manager:
                repository: longhornio/longhorn-manager
                tag: v1.2.5
              ui:
                repository: longhornio/longhorn-ui
                tag: v1.2.5
              instanceManager:
                repository: longhornio/longhorn-instance-manager
                tag: v1_20220303_patch1
              shareManager:
                repository: longhornio/longhorn-share-manager
                tag: v1_20211020_patch1
              backingImageManager:
                repository: longhornio/backing-image-manager
                tag: v2_20210820_patch1
            csi:
              attacher:
                repository: longhornio/csi-attacher
                tag: v3.2.1
              provisioner:
                repository: longhornio/csi-provisioner
                tag: v2.1.2
              nodeDriverRegistrar:
                repository: longhornio/csi-node-driver-registrar
                tag: v2.3.0
              resizer:
                repository: longhornio/csi-resizer
                tag: v1.2.0
              snapshotter:
                repository: longhornio/csi-snapshotter
                tag: v3.0.3
            pullPolicy: IfNotPresent
          service:
            ui:
              type: ClusterIP
              nodePort: null
            manager:
              type: ClusterIP
              nodePort: ""
          persistence:
            defaultClass: true
            defaultFsType: ext4
            defaultClassReplicaCount: 3
            reclaimPolicy: Delete
            migratable: false
            recurringJobSelector:
              enable: false
              jobList: []
            backingImage:
              enable: false
              name: ~
              dataSourceType: ~
              dataSourceParameters: ~
              expectedChecksum: ~
          csi:
            kubeletRootDir: ~
            attacherReplicaCount: ~
            provisionerReplicaCount: ~
            resizerReplicaCount: ~
            snapshotterReplicaCount: ~
          defaultSettings:
            backupTarget: ~
            backupTargetCredentialSecret: ~
            allowRecurringJobWhileVolumeDetached: ~
            createDefaultDiskLabeledNodes: ~
            defaultDataPath: /home/longhorn/data
            defaultDataLocality: ~
            replicaSoftAntiAffinity: ~
            replicaAutoBalance: ~
            storageOverProvisioningPercentage: ~
            storageMinimalAvailablePercentage: ~
            upgradeChecker: ~
            defaultReplicaCount: 2
            defaultLonghornStaticStorageClass: ~
            backupstorePollInterval: ~
            failedBackupTTL: ~
            taintToleration: ~
            systemManagedComponentsNodeSelector: ~
            priorityClass: ~
            autoSalvage: ~
            autoDeletePodWhenVolumeDetachedUnexpectedly: ~
            disableSchedulingOnCordonedNode: ~
            replicaZoneSoftAntiAffinity: ~
            nodeDownPodDeletionPolicy: ~
            allowNodeDrainWithLastHealthyReplica: ~
            mkfsExt4Parameters: ~
            disableReplicaRebuild: ~
            replicaReplenishmentWaitInterval: ~
            concurrentReplicaRebuildPerNodeLimit: ~
            disableRevisionCounter: ~
            systemManagedPodsImagePullPolicy: ~
            allowVolumeCreationWithDegradedAvailability: ~
            autoCleanupSystemGeneratedSnapshot: ~
            concurrentAutomaticEngineUpgradePerNodeLimit: ~
            backingImageCleanupWaitInterval: ~
            backingImageRecoveryWaitInterval: ~
            guaranteedEngineManagerCPU: ~
            guaranteedReplicaManagerCPU: ~
          privateRegistry:
            registryUrl: ~
            registryUser: ~
            registryPasswd: ~
            registrySecret: ~
          longhornManager:
            priorityClass: ~
            tolerations: []
            nodeSelector: {}
          longhornDriver:
            priorityClass: ~
            tolerations: []
            nodeSelector:
          longhornUI:
            priorityClass: ~
            tolerations: []
            nodeSelector: {}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ingress:
            ## Set to true to enable ingress record generation
            enabled: false
            ingressClassName: ~
            host: sslip.io
            tls: false
            tlsSecret: longhorn.local-tls
          # Configure a pod security policy in the Longhorn namespace to allow privileged pods
          enablePSP: true
          namespaceOverride: "longhorn-system"
          # Annotations to add to the Longhorn Manager DaemonSet Pods. Optional.
          annotations: {}

          serviceAccount:
            # Annotations to add to the service account
            annotations: {}

  destination:
    namespace: longhorn-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=background
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
