apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
spec:
  project: core
  source:
    repoURL: 'https://github.com/gruberdev/homelab.git'
    path: apps/data/nfs
    targetRevision: main
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: true
    syncOptions:
    - Validate=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    retry:
      limit: 1
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
