apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
spec:
  project: cluster
  source:
    repoURL: https://github.com/spotahome/redis-operator.git
    targetRevision: master
    path: charts/redisoperator/
    helm:
      skipCrds: true
      releaseName: redis-operator
      values: |
          image:
            repository: quay.io/spotahome/redis-operator
            pullPolicy: IfNotPresent
            tag: v1.2.2
          imageCredentials:
            create: false
          updateStrategy:
            type: Recreate
          replicas: 1
          nameOverride: ""
          # A name to substitute for the full names of resources.
          fullnameOverride: ""
          serviceAccount:
            create: true
            annotations: {}
            name: ""
          service:
            type: ClusterIP
            port: 9710
          container:
            port: 9710
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          monitoring:
            enabled: false
            serviceMonitor: false
            serviceAnnotations: {}
            prometheus:
              name: unknown
          annotations: {}
          nodeSelector:
            kubernetes.io/hostname: node-two
          tolerations: []
          affinity: {}

  destination:
    namespace: databases
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=background
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
