apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-loadbalancer
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: https://clrxbl.github.io/tailscale-svc-lb/
    chart: tailscale-svc-lb
    targetRevision: 1.0.0
    helm:
      releaseName: tailscale-lb
  destination:
    namespace: kube-system
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
