apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: networking
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.13.1
      helm:
        releaseName: external-dns
        namespace: networking
        valueFiles:
        - $values/apps/networking/external-dns/cvalues.yaml
      plugin:
        name: argocd-vault-plugin-helm
        env:
          - name: HELM_VALUES
            value: |
              cloudflare:
                apiKey: <path:kv/data/cloudflare#api-key>
                email: <path:kv/data/cloudflare#email>
    - repoURL: https://github.com/kubernetes-sigs/external-dns.git
      path: charts/external-dns
      targetRevision: v0.13.6
      helm:
        releaseName: external-dns
        namespace: networking
        valueFiles:
        - $values/apps/networking/external-dns/cvalues.yaml
    - repoURL: https://github.com/gruberdev/homelab.git
      targetRevision: main
      ref: values
    # Awaiting this PR to be merged https://github.com/gczuczy/argo-cd/blob/multi-source-combine-signedoff/docs/user-guide/multiple_sources.md
    #   plugin:
    #     name: argocd-vault-plugin-helm
    #     env:
    #       - name: HELM_VALUES
    #         value: |
    #           cloudflare:
    #             apiKey: <path:kv/data/cloudflare#api-key>
    #             email: <path:kv/data/cloudflare#email>
  destination:
    namespace: networking
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - ApplyOutOfSyncOnly=false
    - Prune=true
    - RespectIgnoreDifferences=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 15m
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
