apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: networking
  sources:
    - repoURL: https://github.com/gruberdev/homelab.git
      path: apps/networking/external-dns
      targetRevision: main
      helm:
        releaseName: external-dns
        namespace: networking
        valueFiles:
        - https://raw.githubusercontent.com/gruberdev/homelab/main/apps/networking/external-dns/cvalues.yaml
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.13.1
      helm:
        releaseName: external-dns
        namespace: networking
        valueFiles:
        - https://raw.githubusercontent.com/gruberdev/homelab/main/apps/networking/external-dns/cvalues.yaml
    - repoURL: https://github.com/kubernetes-sigs/external-dns.git
      path: charts/external-dns
      targetRevision: v0.13.6
      helm:
        releaseName: external-dns
        namespace: networking
        valueFiles:
        - https://raw.githubusercontent.com/gruberdev/homelab/main/apps/networking/external-dns/cvalues.yaml
  destination:
    namespace: networking
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 15m
