apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base
- https://github.com/gruberdev/homelab/apps/networking/tailscale

namespace: services

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: deploy
  spec:
    template:
      spec:
        containers:
        - name: nginx
          $patch: delete
  EOF

patches:
- path: https://raw.githubusercontent.com/gruberdev/homelab/main/apps/networking/tailscale/patch.yaml
  target:
    kind: Deployment
    name: n8n-server
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/1"
      value:
        name: TS_HOSTNAME
        value: "n8n"
    - op: replace
      path: "/spec/template/spec/containers/0/env/2"
      value:
        name: DEST_PORT
        value: "5678"
  target:
    kind: Deployment
    name: n8n-server
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: "node2"
  target:
    kind: Deployment
commonAnnotations:
  reloader.stakater.com/auto: "true"
images:
- name: n8nio/n8n
  newTag: 0.193.5
