apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/drone/charts.git'
    targetRevision: master
    path: charts/drone
    helm:
      releaseName: drone-server
      values: |
        serviceAccount:
          create: true
          name: drone-sa
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        persistentVolume:
          enabled: true
          accessModes:
            - ReadWriteOnce
          existingClaim: ""
          mountPath: /data
          size: 8Gi
          storageClass: ""
          volumeMode: ""
          subPath: ""
        emptyDir:
          sizeLimit: ""


  destination:
    namespace: drone
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=background
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
