apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: drone-db
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-14:2.1-p6
  teamId: "home-apps"
  numberOfInstances: 2
  users:
    admin:
    - superuser
    - createdb
    homeuser: []
  databases:
    drone: admin
  postgresql:
    version: "14"
  # Prevents PostgreSQL 64mb limit
  enableShmVolume: true
  enableMasterLoadBalancer: true
  enableConnectionPooler: true
  # Load balancers' source ranges for both master and replica services
  volume:
    size: 5Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
