apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-server
  namespace: drone
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
