apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drone-kube-runner
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cluster
  source:
    repoURL: 'https://github.com/drone/charts.git'
    targetRevision: master
    path: charts/drone
    helm:
      releaseName: drone-kube-runner
      values: |
        args:
          - --namespace=default
          - --delete-successful-after=5m
          - --delete-failed-after=120m
          - --delete-pending-pods-after=60m
          - --delete-evicted-pods-after=60m
          - --delete-orphaned-pods-after=60m
          - --legacy-mode=false

  destination:
    namespace: drone
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=background
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
