apiVersion: v1
kind: Service
metadata:
  name: domainmod
  labels:
    app: domainmod
spec:
  type: ClusterIP
  selector:
    app: domainmod
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
