---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
  annotations:
    link.argocd.argoproj.io/external-link: https://tv.gruber.dev.br
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      runtimeClassName: nvidia
      containers:
        - name: jellyfin
          image: docker.io/jellyfin/jellyfin:20230807.3-unstable
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: 8096
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: jellyfin-cm
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
            - name: https
              containerPort: 8920
              protocol: TCP
            - name: discovery
              containerPort: 7359
              protocol: UDP
            - name: dnla
              containerPort: 1900
              protocol: UDP
          resources:
            requests:
              cpu: 150m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          volumeMounts:
            - name: movies
              mountPath: /movies
            - name: anime
              mountPath: /anime
            - name: cache
              mountPath: /cache
            - name: config
              mountPath: /config
          securityContext:
            privileged: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-storage
        - name: movies
          persistentVolumeClaim:
            claimName: movie-library
        - name: anime
          persistentVolumeClaim:
            claimName: anime-library
        - name: cache
          persistentVolumeClaim:
            claimName: jellyfin-cache
