apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-sidecar
spec:
  template:
    spec:
      serviceAccountName: "tailscale"
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:v1.32.2
          env:
            - name: TS_USERSPACE
              value: "false"
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
            - name: HOSTNAME
              value: "unifi"
            - name: DEST_PORT
              value: "8443"
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "350m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "80Mi"
