apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-sidecar
spec:
  template:
    spec:
      serviceAccountName: "tailscale"
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:v1.30.0
          env:
            - name: USERSPACE
              value: "false"
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
            - name: TS_HOSTNAME
              value: "unifi"
            - name: DEST_PORT
              value: "8443"
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          ports:
            - containerPort: 3478
              name: stun
              protocol: UDP
            - containerPort: 41641
              name: wireguard
              protocol: UDP
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
          livenessProbe:
            exec:
              command:
              - tailscale
              - --socket=/tmp/tailscaled.sock
              - status
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 24
          startupProbe:
            exec:
              command:
              - tailscale
              - --socket=/tmp/tailscaled.sock
              - status
            initialDelaySeconds: 35
            periodSeconds: 30
            failureThreshold: 1
