apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base
- https://github.com/gruberdev/homelab/apps/networking/cloudflared

patchesStrategicMerge:
- overlay/cloudflared-cm.yaml

namespace: rss

patches:
- patch: |-
    - op: replace
      path: "/spec/template/spec/volumes/0/secret/secretName"
      value: "rssgen-tunnel"
  target:
    kind: Deployment
    name: cloudflared
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: node-two
  target:
    kind: Deployment
    name: rss-gen

commonAnnotations:
  reloader.stakater.com/auto: "true"
