apiVersion: v1
kind: Service
metadata:
  name: flame-svc
  labels:
    name: flame
spec:
  type: ClusterIP
  selector:
    app: flame
  ports:
  - name: http
    protocol: TCP
    port: 5005
    targetPort: 5005
