---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-proxy
  labels:
    app: ts-proxy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ts-proxy
  template:
    metadata:
      labels:
        app: ts-proxy
    spec:
      serviceAccountName: "tailscale"
      initContainers:
      - name: sysctler
        image: busybox
        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1
        resources:
          requests:
            cpu: 1m
            memory: 1Mi
      containers:
        - name: proxy
          imagePullPolicy: IfNotPresent
          image: grubertech/tailscale:v1.32.2-4
          env:
            - name: TS_USERSPACE
              value: "false"
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
            - name: TS_HOSTNAME
              value: "service-hostname"
            - name: DEST_PORT
              value: "8443"
            - name: TS_DEST_SVC
              value: "example.svc.cluster.local"
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "100m"
              memory: "150Mi"
            requests:
              cpu: "50m"
              memory: "80Mi"
