apiVersion: v1
kind: Service
metadata:
  name: change-svc
  labels:
    app: change-server
    external-dns.alpha.kubernetes.io/target: onchange.raptor-beta.ts.net
    external-dns.alpha.kubernetes.io/access: private
    tailscale.com/hostname: "onchange"
spec:
  selector:
    app: change-server
  ports:
    - name: web
      port: 80
      targetPort: 5000
      protocol: TCP
  loadBalancerClass: tailscale
  type: LoadBalancer
