apiVersion: v1
kind: Service
metadata:
  name: change-svc
  labels:
    app: change-server
    external-dns.alpha.kubernetes.io/hostname: "nchange.gr.wtf"
    external-dns.alpha.kubernetes.io/access: "public"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    tailscale.com/hostname: "onchange"
spec:
  selector:
    app: change-server
  ports:
    - name: web
      port: 80
      targetPort: 5000
      protocol: TCP
  loadBalancerClass: tailscale
  type: LoadBalancer
