---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
  labels:
    app: router
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      serviceAccountName: "tailscale"
      containers:
        - name: router
          imagePullPolicy: Always
          image: grubertech/tailscale:v1.34.1-1
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          env:
            - name: USERSPACE
              value: "false"
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
            - name: TS_HOSTNAME
              value: "router"
            - name: ROUTES
              value: "10.43.0.0/16,10.42.0.0/24"
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale
                  key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
