apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  type: ClusterIP
  clusterIP: 10.43.173.87
  selector:
    app: router
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
