apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: db-whats-bridge
spec:
  dockerImage: registry.opensource.zalan.do/acid/spilo-14:2.1-p6
  teamId: "db"
  numberOfInstances: 1
  users:
    admin:
    - superuser
    - createdb
    matrix: []
  databases:
    whats: matrix
  postgresql:
    version: "14"
  volume:
    size: 5Gi
    storageClass: longhorn
  resources:
    requests:
      cpu: 150m
      memory: 350Mi
    limits:
      cpu: 200m
      memory: 510Mi
