apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  replicas: 1
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: home-assistant
          image: docker.io/homeassistant/home-assistant:2022.8
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8123
              protocol: TCP
          securityContext:
            privileged: true
          livenessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: api
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: TZ
              value: America/Sao_Paulo
            - name: PYTHONWARNINGS
              value: ignore:Unverified HTTPS request
          volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: dev-usb-00
            mountPath: "/dev/ttyUSB0"
          - name: dev-usb-01
            mountPath: "/dev/ttyUSB1"
          - name: zigbee-00
            mountPath: "/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130205F-if00-port0"
          - name: zigbee-01
            mountPath: "/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130205F-if01-port0"
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: home-assisstant-pvc
        - name: zigbee-00
          hostPath:
            path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130205F-if00-port0
        - name: zigbee-01
          hostPath:
            path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_C130205F-if01-port0
        - name: dev-usb-00
          hostPath:
            path: /dev/ttyUSB0
        - name: dev-usb-01
          hostPath:
            path: /dev/ttyUSB1
      restartPolicy: Always
