apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  type: LoadBalancer
  loadBalancerClass: "svc-lb.tailscale.iptables.sh/lb"
  allocateLoadBalancerNodePorts: false
  selector:
    app: home-assistant
  ports:
  - name: ha
    port: 80
    protocol: TCP
    targetPort: 8123

