apiVersion: v1
kind: Service
metadata:
  name: home-assistant-service
  labels:
    app: home-assistant
#  annotations:
#    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: home-assistant
  type: NodePort
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123
      nodePort: 31123
