apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ./base
- https://github.com/gruberdev/homelab/apps/networking/tailscale
patchesStrategicMerge:
- overlay/changes-statefulset.yaml

namespace: services

commonAnnotations:
  reloader.stakater.com/auto: "true"
