apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agones-crds
spec:
  project: apps
  source:
    repoURL: https://github.com/googleforgames/agones.git
    targetRevision: v1.28.0
    path: install/helm/agones/templates/crds
    directory:
      recurse: true
  destination:
    namespace: gaming
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
