apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
spec:
  project: apps
  source:
    repoURL: https://github.com/blakeblackshear/blakeshome-charts.git
    targetRevision: frigate-7.0.0
    path: charts/frigate
    helm:
      releaseName: frigate
      values: |
        strategyType: Recreate
        image:
          repository: blakeblackshear/frigate
          tag: 0.11.0
          pullPolicy: IfNotPresent
        imagePullSecrets: []
        env:
          TZ: America/Sao_Paulo
        envFromSecrets: []
          # secrets are required before `helm install`
          # - frigate-rstp-credentials
        coral:
          enabled: false
        gpu:
          nvidia:
            enabled: true
            runtimeClassName: "nvidia"
        extraVolumes: []
        extraVolumeMounts: []
        shmSize: 1Gi
        config: |
          rtmp:
            enabled: True
          mqtt:
            enabled: False
          record:
            enabled: False
          ui:
            order: 0
            dashboard: True
          cameras:
            home_feed:
              ffmpeg:
                inputs:
                  - path: rtsp://wyze-bridge.homeassistant.svc.cluster.local:8554
                    roles:
                      - detect
                      - rtmp
        probes:
          liveness:
            enabled: true
            initialDelaySeconds: 30
            failureThreshold: 5
            timeoutSeconds: 10
          readiness:
            enabled: true
            initialDelaySeconds: 20
            failureThreshold: 5
            timeoutSeconds: 10
          startup:
            enabled: true
            failureThreshold: 60
            periodSeconds: 60
        service:
          type: ClusterIP
          port: 5000
          annotations: {}
          labels: {}
          loadBalancerIP:
        ingress:
          enabled: false
        persistence:
          data:
            enabled: true
            storageClass: longhorn
            existingClaim: frigate-storage
            accessMode: ReadWriteOnce
            size: 10Gi
            skipuninstall: false
        resources:
          limits:
            cpu: 350m
            memory: 512Mi
          requests:
            cpu: 150m
            memory: 256Mi
        securityContext: {}
        nodeSelector:
          kubernetes.io/hostname: node-two
          kubernetes.io/arch: amd64
        tolerations: []
        affinity: {}
        podAnnotations: {}

  destination:
    namespace: homeassistant
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
    - Validate=false
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSyncOnly=false
    - Prune=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
