apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-server
  labels:
    app: drone
spec:
  selector:
    matchLabels:
      app: drone
  replicas: 1
  template:
    metadata:
      labels:
        app: drone
    spec:
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:latest
          env:
          - name: USERSPACE
            valeu: "false"
          - name: TS_HOSTNAME
            value: "drone"
          - name: DEST_PORT
            value: "80"
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: tailscale
                key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      serviceAccount: tailscale
