apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: changedetection
  labels:
    app: changedetection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changedetection
  serviceName: "changedetection"
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: grubertech/tailscale:latest
          env:
          - name: USERSPACE
            value: "false"
          - name: TS_HOSTNAME
            value: "onchanges"
          - name: DEST_PORT
            value: "5000"
          - name: AUTH_KEY
            valueFrom:
              secretKeyRef:
                name: tailscale
                key: AUTH_KEY
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          resources:
            limits:
              cpu: "256m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
        - name: changedetection
          image: dgtlmoon/changedetection.io:latest
          imagePullPolicy: IfNotPresen
          ports:
          - name: http
            containerPort: 5000
          resources:
            limits:
              memory: "350Mi"
            requests:
              memory: "120Mi"
          volumeMounts:
          - name: onchange-data
            readOnly: false
            mountPath: "/datastore"
          livenessProbe:
            exec:
              command:
              - ls
              - /datastore/lost+found
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
      - name: onchange-data
        persistentVolumeClaim:
          claimName: onchange-storage
