name: tflint
on: [pull_request]
jobs:
  tflint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Clone repo
        uses: actions/checkout@master
      - name: Install Terraform
        run: |
          curl iac.sh/terraform > getinst.sh && \
          bash getinst.sh
      - name: Terraform init
        run: |
          cd terraform && \
          terraform init -upgrade -backend-config="conn_str=${{ secrets.tf_con_string }}"
      - name: tflint
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: "terraform"
          reporter: github-pr-review
          fail_on_error: "true"
          flags: "--module"
          filter_mode: "nofilter"
