apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- https://github.com/gruberdev/homelab/apps/networking/tailscale/proxy
- https://github.com/gruberdev/homelab/apps/networking/tailscale

namespace: matrix

patches:
- patch: |-
    - op: add
      path: "/spec/template/spec/nodeSelector"
      value:
        kubernetes.io/hostname: node-two
  target:
    kind: Deployment
    name: ts-proxy
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/2"
      value:
        name: TS_HOSTNAME
        value: "matrix"
    - op: replace
      path: "/spec/template/spec/containers/0/env/3"
      value:
        name: DEST_PORT
        value: "80"
    - op: replace
      path: "/spec/template/spec/containers/0/env/4"
      value:
        name: TS_DEST_SVC
        value: "matrix-matrix-synapse.matrix.svc.cluster.local"
  target:
    kind: Deployment
    name: ts-proxy

commonAnnotations:
  reloader.stakater.com/auto: "true"
